on:
  pull_request:
    types:
      - opened
      - reopened
      - unlabeled

permissions:
  contents: read
  pull-requests: write

name: Label Enforcement

jobs:
  label:
    runs-on: ubuntu-latest
    env:
      VALID_LABEL_FOUND: "false"

    steps:
      - name: Check for "major" Label
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: |
          echo "Found 'major' label."
          echo "VALID_LABEL_FOUND=true" >> $GITHUB_ENV

      - name: Check for "minor" Label
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: |
          echo "Found 'minor' label."
          echo "VALID_LABEL_FOUND=true" >> $GITHUB_ENV

      - name: Check for "patch" Label
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: |
          echo "Found 'patch' label."
          echo "VALID_LABEL_FOUND=true" >> $GITHUB_ENV

      - name: Add "minor" Label (Default)
        if: env.VALID_LABEL_FOUND == 'false'
        run: |
          echo "No valid label found. Adding 'minor'."
          gh pr edit ${{ github.event.pull_request.number }} --add-label "minor"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
