on:
  pull_request:
    types:
      - opened
      - reopened
      - unlabeled

permissions:
  contents: write
  pull-requests: write

name: Version Bump

jobs:
  bump:
    name: Bump
    uses: gitops-ci-cd/.github/.github/workflows/version_bump.yaml@main
